
// This file has been generated by the GUI designer. Do not modify.
namespace MatrixResourceManager
{
	public partial class DialogConnectToServer
	{
		private global::Gtk.VBox vbox19;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Frame frame13;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.VBox vbox20;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.VBox vbox21;
		
		private global::Gtk.Entry entry10;
		
		private global::Gtk.Entry entry13;
		
		private global::Gtk.VBox vbox22;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.Label label19;
		
		private global::Gtk.VBox vbox23;
		
		private global::Gtk.Entry entry11;
		
		private global::Gtk.Entry entry12;
		
		private global::Gtk.Label GtkLabel3;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.CheckButton checkbutton1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Button button65;
		
		private global::Gtk.Button buttonCancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MatrixResourceManager.DialogConnectToServer
			this.Name = "MatrixResourceManager.DialogConnectToServer";
			this.Title = global::Mono.Unix.Catalog.GetString ("Connect to Server");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child MatrixResourceManager.DialogConnectToServer.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox19 = new global::Gtk.VBox ();
			this.vbox19.Name = "vbox19";
			this.vbox19.Spacing = 6;
			// Container child vbox19.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Connect to Matrix Server");
			this.vbox19.Add (this.label14);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.label14]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox19.Gtk.Box+BoxChild
			this.frame13 = new global::Gtk.Frame ();
			this.frame13.Name = "frame13";
			this.frame13.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame13.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox20 = new global::Gtk.VBox ();
			this.vbox20.Name = "vbox20";
			this.vbox20.Spacing = 6;
			// Container child vbox20.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Server IP");
			this.vbox20.Add (this.label16);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.label16]));
			w3.Position = 0;
			// Container child vbox20.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Login User");
			this.vbox20.Add (this.label17);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.label17]));
			w4.Position = 1;
			this.hbox9.Add (this.vbox20);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox20]));
			w5.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox21 = new global::Gtk.VBox ();
			this.vbox21.Name = "vbox21";
			this.vbox21.Spacing = 6;
			// Container child vbox21.Gtk.Box+BoxChild
			this.entry10 = new global::Gtk.Entry ();
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '•';
			this.vbox21.Add (this.entry10);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.entry10]));
			w6.Position = 0;
			// Container child vbox21.Gtk.Box+BoxChild
			this.entry13 = new global::Gtk.Entry ();
			this.entry13.Sensitive = false;
			this.entry13.CanFocus = true;
			this.entry13.Name = "entry13";
			this.entry13.IsEditable = true;
			this.entry13.InvisibleChar = '•';
			this.vbox21.Add (this.entry13);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.entry13]));
			w7.Position = 1;
			this.hbox9.Add (this.vbox21);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox21]));
			w8.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox22 = new global::Gtk.VBox ();
			this.vbox22.Name = "vbox22";
			this.vbox22.Spacing = 6;
			// Container child vbox22.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("TCP Port");
			this.vbox22.Add (this.label18);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox22 [this.label18]));
			w9.Position = 0;
			// Container child vbox22.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Login Password");
			this.vbox22.Add (this.label19);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox22 [this.label19]));
			w10.Position = 1;
			this.hbox9.Add (this.vbox22);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox22]));
			w11.Position = 2;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox23 = new global::Gtk.VBox ();
			this.vbox23.Name = "vbox23";
			this.vbox23.Spacing = 6;
			// Container child vbox23.Gtk.Box+BoxChild
			this.entry11 = new global::Gtk.Entry ();
			this.entry11.CanFocus = true;
			this.entry11.Name = "entry11";
			this.entry11.Text = global::Mono.Unix.Catalog.GetString ("14928");
			this.entry11.IsEditable = true;
			this.entry11.InvisibleChar = '•';
			this.vbox23.Add (this.entry11);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox23 [this.entry11]));
			w12.Position = 0;
			// Container child vbox23.Gtk.Box+BoxChild
			this.entry12 = new global::Gtk.Entry ();
			this.entry12.Sensitive = false;
			this.entry12.CanFocus = true;
			this.entry12.Name = "entry12";
			this.entry12.IsEditable = true;
			this.entry12.Visibility = false;
			this.entry12.InvisibleChar = '•';
			this.vbox23.Add (this.entry12);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox23 [this.entry12]));
			w13.Position = 1;
			this.hbox9.Add (this.vbox23);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox23]));
			w14.Position = 3;
			this.GtkAlignment2.Add (this.hbox9);
			this.frame13.Add (this.GtkAlignment2);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Matrix Server Infomation</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame13.LabelWidget = this.GtkLabel3;
			this.vbox19.Add (this.frame13);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.frame13]));
			w17.Position = 1;
			// Container child vbox19.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.hbox8.Add (this.vbox3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox3]));
			w18.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.checkbutton1 = new global::Gtk.CheckButton ();
			this.checkbutton1.Sensitive = false;
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("Anonymous Login");
			this.checkbutton1.Active = true;
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.vbox4.Add (this.checkbutton1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.checkbutton1]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox8.Add (this.vbox4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox4]));
			w20.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.hbox8.Add (this.vbox2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox2]));
			w21.Position = 2;
			this.vbox19.Add (this.hbox8);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.hbox8]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox19.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("* This version doesn't support Matrix Server authenticaion login. It will be supported in next release.");
			this.vbox19.Add (this.label15);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.label15]));
			w23.Position = 3;
			w23.Expand = false;
			w23.Fill = false;
			w1.Add (this.vbox19);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox19]));
			w24.Position = 0;
			// Internal child MatrixResourceManager.DialogConnectToServer.ActionArea
			global::Gtk.HButtonBox w25 = this.ActionArea;
			w25.Name = "dialog1_ActionArea";
			w25.Spacing = 10;
			w25.BorderWidth = ((uint)(5));
			w25.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button65 = new global::Gtk.Button ();
			this.button65.CanFocus = true;
			this.button65.Name = "button65";
			this.button65.UseUnderline = true;
			this.button65.Label = global::Mono.Unix.Catalog.GetString ("Connect");
			this.AddActionWidget (this.button65, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w25 [this.button65]));
			w26.Expand = false;
			w26.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w25 [this.buttonCancel]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 686;
			this.DefaultHeight = 271;
			this.Show ();
			this.button65.Clicked += new global::System.EventHandler (this.OnButton65Clicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
		}
	}
}
