
// This file has been generated by the GUI designer. Do not modify.
namespace MatrixResourceManager
{
	public partial class WidgetMonitor
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.ComboBox combobox4;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.ComboBox combobox5;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview2;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Button button74;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Button button29;
		
		private global::Gtk.Button button30;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.DrawingArea drawingarea2;
		
		private global::Gtk.Alignment alignment2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MatrixResourceManager.WidgetMonitor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MatrixResourceManager.WidgetMonitor";
			// Container child MatrixResourceManager.WidgetMonitor.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Select GPU Server");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.combobox4 = global::Gtk.ComboBox.NewText ();
			this.combobox4.Name = "combobox4";
			this.vbox5.Add (this.combobox4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.combobox4]));
			w2.Position = 0;
			w2.Fill = false;
			this.hbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox5]));
			w3.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w4.Position = 0;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Select Metric");
			this.hbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.combobox5 = global::Gtk.ComboBox.NewText ();
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("GPU Utilization\t\t(%)"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("Memory Utilization \t(%)"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("Power Draw \t\t\t(Watt)"));
			this.combobox5.AppendText (global::Mono.Unix.Catalog.GetString ("Temperature \t\t\t(°C)"));
			this.combobox5.Name = "combobox5";
			this.combobox5.Active = 0;
			this.vbox6.Add (this.combobox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.combobox5]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox4.Add (this.vbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox6]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView ();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.GtkScrolledWindow.Add (this.treeview2);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.frame2.Add (this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("Select GPU Cards");
			this.GtkLabel2.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel2;
			this.hbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame2]));
			w13.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Time Frame (sec)");
			this.vbox8.Add (this.label4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label4]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.Text = global::Mono.Unix.Catalog.GetString ("180");
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.vbox8.Add (this.entry1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.entry1]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.button74 = new global::Gtk.Button ();
			this.button74.Sensitive = false;
			this.button74.CanFocus = true;
			this.button74.Name = "button74";
			this.button74.UseUnderline = true;
			this.button74.Label = global::Mono.Unix.Catalog.GetString ("Update");
			this.vbox8.Add (this.button74);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.button74]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.hbox1.Add (this.vbox8);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox8]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button29 = new global::Gtk.Button ();
			this.button29.CanFocus = true;
			this.button29.Name = "button29";
			this.button29.UseUnderline = true;
			this.button29.Label = global::Mono.Unix.Catalog.GetString ("Start");
			this.vbox4.Add (this.button29);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button29]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button30 = new global::Gtk.Button ();
			this.button30.Sensitive = false;
			this.button30.CanFocus = true;
			this.button30.Name = "button30";
			this.button30.UseUnderline = true;
			this.button30.Label = global::Mono.Unix.Catalog.GetString ("Stop");
			this.vbox4.Add (this.button30);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button30]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.drawingarea2 = new global::Gtk.DrawingArea ();
			this.drawingarea2.Name = "drawingarea2";
			this.alignment1.Add (this.drawingarea2);
			this.vbox2.Add (this.alignment1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment1]));
			w23.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.vbox2.Add (this.alignment2);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment2]));
			w24.Position = 2;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.button29.Clicked += new global::System.EventHandler (this.OnButton29Clicked);
			this.button30.Clicked += new global::System.EventHandler (this.OnButton30Clicked);
			this.drawingarea2.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawingarea2ExposeEvent);
		}
	}
}
