
// This file has been generated by the GUI designer. Do not modify.
namespace MatrixResourceManager
{
	public partial class WidgetDashboardView
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MatrixResourceManager.WidgetDashboardView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MatrixResourceManager.WidgetDashboardView";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
