
// This file has been generated by the GUI designer. Do not modify.
namespace MatrixResourceManager
{
	public partial class WidgetAssignmentView
	{
		private global::Gtk.VBox vbox12;
		
		private global::Gtk.Frame frame9;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview4;
		
		private global::Gtk.Label GtkLabel;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.VBox vbox13;
		
		private global::Gtk.Frame frame11;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView treeview5;
		
		private global::Gtk.Label GtkLabel1;
		
		private global::Gtk.VBox vbox14;
		
		private global::Gtk.Frame frame12;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.VBox vbox15;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.VBox vbox16;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.VBox vbox17;
		
		private global::Gtk.ComboBox combobox2;
		
		private global::Gtk.VBox vbox18;
		
		private global::Gtk.Button button48;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.TreeView treeview6;
		
		private global::Gtk.Label GtkLabel6;
		
		private global::Gtk.HButtonBox hbuttonbox4;
		
		private global::Gtk.Button button43;
		
		private global::Gtk.Button button44;
		
		private global::Gtk.Button button45;
		
		private global::Gtk.Button button46;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MatrixResourceManager.WidgetAssignmentView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MatrixResourceManager.WidgetAssignmentView";
			// Container child MatrixResourceManager.WidgetAssignmentView.Gtk.Container+ContainerChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.frame9 = new global::Gtk.Frame ();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame9.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview4 = new global::Gtk.TreeView ();
			this.treeview4.CanFocus = true;
			this.treeview4.Name = "treeview4";
			this.GtkScrolledWindow.Add (this.treeview4);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.frame9.Add (this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GPU Resource List</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame9.LabelWidget = this.GtkLabel;
			this.vbox12.Add (this.frame9);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.frame9]));
			w4.Position = 0;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.frame11 = new global::Gtk.Frame ();
			this.frame11.Name = "frame11";
			this.frame11.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame11.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview5 = new global::Gtk.TreeView ();
			this.treeview5.CanFocus = true;
			this.treeview5.Name = "treeview5";
			this.GtkScrolledWindow1.Add (this.treeview5);
			this.GtkAlignment1.Add (this.GtkScrolledWindow1);
			this.frame11.Add (this.GtkAlignment1);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GPU Information</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame11.LabelWidget = this.GtkLabel1;
			this.vbox13.Add (this.frame11);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.frame11]));
			w8.Position = 0;
			this.hbox6.Add (this.vbox13);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox13]));
			w9.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.frame12 = new global::Gtk.Frame ();
			this.frame12.Name = "frame12";
			this.frame12.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame12.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox15 = new global::Gtk.VBox ();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox ();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Ypad = 8;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Agent IP Address");
			this.vbox16.Add (this.label13);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.label13]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox7.Add (this.vbox16);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox16]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox ();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.combobox2 = global::Gtk.ComboBox.NewText ();
			this.combobox2.Name = "combobox2";
			this.vbox17.Add (this.combobox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.combobox2]));
			w12.Position = 0;
			this.hbox7.Add (this.vbox17);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox17]));
			w13.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox18 = new global::Gtk.VBox ();
			this.vbox18.Name = "vbox18";
			this.vbox18.Spacing = 6;
			// Container child vbox18.Gtk.Box+BoxChild
			this.button48 = new global::Gtk.Button ();
			this.button48.CanFocus = true;
			this.button48.Name = "button48";
			this.button48.UseUnderline = true;
			this.button48.Label = global::Mono.Unix.Catalog.GetString ("Retrieve Agent");
			this.vbox18.Add (this.button48);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.button48]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox7.Add (this.vbox18);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox18]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox15.Add (this.hbox7);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox7]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeview6 = new global::Gtk.TreeView ();
			this.treeview6.CanFocus = true;
			this.treeview6.Name = "treeview6";
			this.GtkScrolledWindow2.Add (this.treeview6);
			this.vbox15.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.GtkScrolledWindow2]));
			w18.Position = 1;
			this.GtkAlignment2.Add (this.vbox15);
			this.frame12.Add (this.GtkAlignment2);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GPU Assignment</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame12.LabelWidget = this.GtkLabel6;
			this.vbox14.Add (this.frame12);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.frame12]));
			w21.Position = 0;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbuttonbox4 = new global::Gtk.HButtonBox ();
			this.hbuttonbox4.Name = "hbuttonbox4";
			this.hbuttonbox4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.button43 = new global::Gtk.Button ();
			this.button43.Sensitive = false;
			this.button43.CanFocus = true;
			this.button43.Name = "button43";
			this.button43.UseUnderline = true;
			this.button43.Label = global::Mono.Unix.Catalog.GetString ("Assign GPU");
			this.hbuttonbox4.Add (this.button43);
			global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button43]));
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.button44 = new global::Gtk.Button ();
			this.button44.Sensitive = false;
			this.button44.CanFocus = true;
			this.button44.Name = "button44";
			this.button44.UseUnderline = true;
			this.button44.Label = global::Mono.Unix.Catalog.GetString ("Remove GPU");
			this.hbuttonbox4.Add (this.button44);
			global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button44]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.button45 = new global::Gtk.Button ();
			this.button45.Sensitive = false;
			this.button45.CanFocus = true;
			this.button45.Name = "button45";
			this.button45.UseUnderline = true;
			this.button45.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.hbuttonbox4.Add (this.button45);
			global::Gtk.ButtonBox.ButtonBoxChild w24 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button45]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.button46 = new global::Gtk.Button ();
			this.button46.Sensitive = false;
			this.button46.CanFocus = true;
			this.button46.Name = "button46";
			this.button46.UseUnderline = true;
			this.button46.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hbuttonbox4.Add (this.button46);
			global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button46]));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox14.Add (this.hbuttonbox4);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbuttonbox4]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.hbox6.Add (this.vbox14);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox14]));
			w27.Position = 1;
			this.vbox12.Add (this.hbox6);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox6]));
			w28.Position = 1;
			this.Add (this.vbox12);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.treeview4.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeview4RowActivated);
			this.button48.Clicked += new global::System.EventHandler (this.OnButton48Clicked);
			this.button43.Clicked += new global::System.EventHandler (this.OnButton43Clicked);
			this.button44.Clicked += new global::System.EventHandler (this.OnButton44Clicked);
			this.button45.Clicked += new global::System.EventHandler (this.OnButton45Clicked);
			this.button46.Clicked += new global::System.EventHandler (this.OnButton46Clicked);
		}
	}
}
