
// This file has been generated by the GUI designer. Do not modify.
namespace MatrixResourceManager
{
	public partial class WidgetAgentsView
	{
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.Frame frame6;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview1;
		
		private global::Gtk.Label GtkLabel4;
		
		private global::Gtk.VBox vbox11;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.Frame frame7;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView treeview2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Frame frame9;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		
		private global::Gtk.TreeView treeview4;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Frame frame10;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		
		private global::Gtk.TreeView treeview5;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Notebook notebook2;
		
		private global::Gtk.Frame frame8;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.TreeView treeview3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Frame frame11;
		
		private global::Gtk.Alignment GtkAlignment5;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow5;
		
		private global::Gtk.TreeView treeview6;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.HButtonBox hbuttonbox3;
		
		private global::Gtk.Button button39;
		
		private global::Gtk.Button button40;
		
		private global::Gtk.Button button41;
		
		private global::Gtk.Button button42;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MatrixResourceManager.WidgetAgentsView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MatrixResourceManager.WidgetAgentsView";
			// Container child MatrixResourceManager.WidgetAgentsView.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.frame6.Add (this.GtkAlignment);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Agent List</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel4;
			this.vbox10.Add (this.frame6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.frame6]));
			w4.Position = 0;
			this.hbox5.Add (this.vbox10);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox10]));
			w5.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 2;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView ();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.GtkScrolledWindow1.Add (this.treeview2);
			this.GtkAlignment1.Add (this.GtkScrolledWindow1);
			this.frame7.Add (this.GtkAlignment1);
			this.notebook1.Add (this.frame7);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("GPU Information");
			this.notebook1.SetTabLabel (this.frame7, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.frame9 = new global::Gtk.Frame ();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame9.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.treeview4 = new global::Gtk.TreeView ();
			this.treeview4.CanFocus = true;
			this.treeview4.Name = "treeview4";
			this.GtkScrolledWindow3.Add (this.treeview4);
			this.GtkAlignment3.Add (this.GtkScrolledWindow3);
			this.frame9.Add (this.GtkAlignment3);
			this.notebook1.Add (this.frame9);
			global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.frame9]));
			w13.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Fabric Information");
			this.notebook1.SetTabLabel (this.frame9, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.frame10 = new global::Gtk.Frame ();
			this.frame10.Name = "frame10";
			this.frame10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame10.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.treeview5 = new global::Gtk.TreeView ();
			this.treeview5.CanFocus = true;
			this.treeview5.Name = "treeview5";
			this.GtkScrolledWindow4.Add (this.treeview5);
			this.GtkAlignment4.Add (this.GtkScrolledWindow4);
			this.frame10.Add (this.GtkAlignment4);
			this.notebook1.Add (this.frame10);
			global::Gtk.Notebook.NotebookChild w17 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.frame10]));
			w17.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Assignment");
			this.notebook1.SetTabLabel (this.frame10, this.label3);
			this.label3.ShowAll ();
			this.vbox11.Add (this.notebook1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.notebook1]));
			w18.Position = 0;
			// Container child vbox11.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 0;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.frame8 = new global::Gtk.Frame ();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeview3 = new global::Gtk.TreeView ();
			this.treeview3.CanFocus = true;
			this.treeview3.Name = "treeview3";
			this.GtkScrolledWindow2.Add (this.treeview3);
			this.GtkAlignment2.Add (this.GtkScrolledWindow2);
			this.frame8.Add (this.GtkAlignment2);
			this.notebook2.Add (this.frame8);
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Server Runtime Config");
			this.notebook2.SetTabLabel (this.frame8, this.label4);
			this.label4.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.frame11 = new global::Gtk.Frame ();
			this.frame11.Name = "frame11";
			this.frame11.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame11.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
			this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
			this.treeview6 = new global::Gtk.TreeView ();
			this.treeview6.CanFocus = true;
			this.treeview6.Name = "treeview6";
			this.GtkScrolledWindow5.Add (this.treeview6);
			this.GtkAlignment5.Add (this.GtkScrolledWindow5);
			this.frame11.Add (this.GtkAlignment5);
			this.notebook2.Add (this.frame11);
			global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.frame11]));
			w26.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Client Runtime Config");
			this.notebook2.SetTabLabel (this.frame11, this.label5);
			this.label5.ShowAll ();
			this.vbox11.Add (this.notebook2);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.notebook2]));
			w27.Position = 1;
			this.hbox5.Add (this.vbox11);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox11]));
			w28.Position = 1;
			this.vbox9.Add (this.hbox5);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox5]));
			w29.Position = 0;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbuttonbox3 = new global::Gtk.HButtonBox ();
			this.hbuttonbox3.Name = "hbuttonbox3";
			this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.button39 = new global::Gtk.Button ();
			this.button39.CanFocus = true;
			this.button39.Name = "button39";
			this.button39.UseUnderline = true;
			this.button39.Label = global::Mono.Unix.Catalog.GetString ("New Agent");
			this.hbuttonbox3.Add (this.button39);
			global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button39]));
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.button40 = new global::Gtk.Button ();
			this.button40.CanFocus = true;
			this.button40.Name = "button40";
			this.button40.UseUnderline = true;
			this.button40.Label = "Remove Agent";
			this.hbuttonbox3.Add (this.button40);
			global::Gtk.ButtonBox.ButtonBoxChild w31 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button40]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.button41 = new global::Gtk.Button ();
			this.button41.CanFocus = true;
			this.button41.Name = "button41";
			this.button41.UseUnderline = true;
			this.button41.Label = global::Mono.Unix.Catalog.GetString ("Download Config");
			this.hbuttonbox3.Add (this.button41);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button41]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.button42 = new global::Gtk.Button ();
			this.button42.CanFocus = true;
			this.button42.Name = "button42";
			this.button42.UseUnderline = true;
			this.button42.Label = global::Mono.Unix.Catalog.GetString ("Restart Agent");
			this.hbuttonbox3.Add (this.button42);
			global::Gtk.ButtonBox.ButtonBoxChild w33 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button42]));
			w33.Position = 3;
			w33.Expand = false;
			w33.Fill = false;
			this.vbox9.Add (this.hbuttonbox3);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbuttonbox3]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			this.Add (this.vbox9);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.treeview1.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeview1RowActivated);
			this.button39.Clicked += new global::System.EventHandler (this.OnButton39Clicked);
			this.button40.Clicked += new global::System.EventHandler (this.OnButton40Clicked);
			this.button41.Clicked += new global::System.EventHandler (this.OnButton41Clicked);
			this.button42.Clicked += new global::System.EventHandler (this.OnButton42Clicked);
		}
	}
}
