
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.HButtonBox hbuttonbox1;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Button button64;
	
	private global::Gtk.Button button66;
	
	private global::Gtk.HButtonBox hbuttonbox4;
	
	private global::Gtk.Button button186;
	
	private global::Gtk.Button button187;
	
	private global::Gtk.Button button188;
	
	private global::Gtk.Button button190;
	
	private global::Gtk.ScrolledWindow scrolledwindow1;
	
	private global::Gtk.TextView textview1;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.HButtonBox hbuttonbox2;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.Button button63;
	
	private global::Gtk.Button button65;
	
	private global::Gtk.HButtonBox hbuttonbox5;
	
	private global::Gtk.Button button189;
	
	private global::Gtk.Button button191;
	
	private global::Gtk.Button button192;
	
	private global::Gtk.Button button193;
	
	private global::Gtk.ScrolledWindow scrolledwindow2;
	
	private global::Gtk.TextView textview2;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.HButtonBox hbuttonbox3;
	
	private global::Gtk.Button button5;
	
	private global::Gtk.Button button6;
	
	private global::Gtk.Button button61;
	
	private global::Gtk.Button button155;
	
	private global::Gtk.HButtonBox hbuttonbox6;
	
	private global::Gtk.Button button194;
	
	private global::Gtk.Button button195;
	
	private global::Gtk.Button button196;
	
	private global::Gtk.Button button197;
	
	private global::Gtk.ScrolledWindow scrolledwindow3;
	
	private global::Gtk.TextView textview3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulate GUI ");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox ();
		this.hbuttonbox1.Name = "hbuttonbox1";
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("HS w/Srv");
		this.hbuttonbox1.Add (this.button2);
		global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button2]));
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Get GUID");
		this.hbuttonbox1.Add (this.button1);
		global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button64 = new global::Gtk.Button ();
		this.button64.CanFocus = true;
		this.button64.Name = "button64";
		this.button64.UseUnderline = true;
		this.button64.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox1.Add (this.button64);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button64]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button66 = new global::Gtk.Button ();
		this.button66.CanFocus = true;
		this.button66.Name = "button66";
		this.button66.UseUnderline = true;
		this.button66.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox1.Add (this.button66);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button66]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add (this.hbuttonbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox4 = new global::Gtk.HButtonBox ();
		this.hbuttonbox4.Name = "hbuttonbox4";
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button186 = new global::Gtk.Button ();
		this.button186.CanFocus = true;
		this.button186.Name = "button186";
		this.button186.UseUnderline = true;
		this.button186.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox4.Add (this.button186);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button186]));
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button187 = new global::Gtk.Button ();
		this.button187.CanFocus = true;
		this.button187.Name = "button187";
		this.button187.UseUnderline = true;
		this.button187.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox4.Add (this.button187);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button187]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button188 = new global::Gtk.Button ();
		this.button188.CanFocus = true;
		this.button188.Name = "button188";
		this.button188.UseUnderline = true;
		this.button188.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox4.Add (this.button188);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button188]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this.button190 = new global::Gtk.Button ();
		this.button190.CanFocus = true;
		this.button190.Name = "button190";
		this.button190.UseUnderline = true;
		this.button190.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox4.Add (this.button190);
		global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.button190]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add (this.hbuttonbox4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox4]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.scrolledwindow1.Add (this.textview1);
		this.vbox1.Add (this.scrolledwindow1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow1]));
		w13.Position = 4;
		this.hbox1.Add (this.vbox1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
		w14.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulate Matrix Server");
		this.vbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox ();
		this.hbuttonbox2.Name = "hbuttonbox2";
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Start Server");
		this.hbuttonbox2.Add (this.button4);
		global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button4]));
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Push Assignment");
		this.hbuttonbox2.Add (this.button3);
		global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button3]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.button63 = new global::Gtk.Button ();
		this.button63.CanFocus = true;
		this.button63.Name = "button63";
		this.button63.UseUnderline = true;
		this.button63.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox2.Add (this.button63);
		global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button63]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.button65 = new global::Gtk.Button ();
		this.button65.CanFocus = true;
		this.button65.Name = "button65";
		this.button65.UseUnderline = true;
		this.button65.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox2.Add (this.button65);
		global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button65]));
		w19.Position = 3;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox2.Add (this.hbuttonbox2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbuttonbox5 = new global::Gtk.HButtonBox ();
		this.hbuttonbox5.Name = "hbuttonbox5";
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button189 = new global::Gtk.Button ();
		this.button189.CanFocus = true;
		this.button189.Name = "button189";
		this.button189.UseUnderline = true;
		this.button189.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox5.Add (this.button189);
		global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button189]));
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button191 = new global::Gtk.Button ();
		this.button191.CanFocus = true;
		this.button191.Name = "button191";
		this.button191.UseUnderline = true;
		this.button191.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox5.Add (this.button191);
		global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button191]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button192 = new global::Gtk.Button ();
		this.button192.CanFocus = true;
		this.button192.Name = "button192";
		this.button192.UseUnderline = true;
		this.button192.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox5.Add (this.button192);
		global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button192]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this.button193 = new global::Gtk.Button ();
		this.button193.CanFocus = true;
		this.button193.Name = "button193";
		this.button193.UseUnderline = true;
		this.button193.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox5.Add (this.button193);
		global::Gtk.ButtonBox.ButtonBoxChild w24 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button193]));
		w24.Position = 3;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox2.Add (this.hbuttonbox5);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox5]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow2.Gtk.Container+ContainerChild
		this.textview2 = new global::Gtk.TextView ();
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.scrolledwindow2.Add (this.textview2);
		this.vbox2.Add (this.scrolledwindow2);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.scrolledwindow2]));
		w27.Position = 4;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w28.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulate Matrix Agent");
		this.vbox3.Add (this.label3);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label3]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbuttonbox3 = new global::Gtk.HButtonBox ();
		this.hbuttonbox3.Name = "hbuttonbox3";
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Start Agent");
		this.hbuttonbox3.Add (this.button5);
		global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button5]));
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("Chk Agent RegStat");
		this.hbuttonbox3.Add (this.button6);
		global::Gtk.ButtonBox.ButtonBoxChild w31 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button6]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button61 = new global::Gtk.Button ();
		this.button61.CanFocus = true;
		this.button61.Name = "button61";
		this.button61.UseUnderline = true;
		this.button61.Label = global::Mono.Unix.Catalog.GetString ("Upd Agent Status");
		this.hbuttonbox3.Add (this.button61);
		global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button61]));
		w32.Position = 2;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.button155 = new global::Gtk.Button ();
		this.button155.CanFocus = true;
		this.button155.Name = "button155";
		this.button155.UseUnderline = true;
		this.button155.Label = global::Mono.Unix.Catalog.GetString ("rCuda Srv Conf");
		this.hbuttonbox3.Add (this.button155);
		global::Gtk.ButtonBox.ButtonBoxChild w33 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.button155]));
		w33.Position = 3;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox3.Add (this.hbuttonbox3);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbuttonbox3]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbuttonbox6 = new global::Gtk.HButtonBox ();
		this.hbuttonbox6.Name = "hbuttonbox6";
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button194 = new global::Gtk.Button ();
		this.button194.CanFocus = true;
		this.button194.Name = "button194";
		this.button194.UseUnderline = true;
		this.button194.Label = global::Mono.Unix.Catalog.GetString ("rCuda Client Conf");
		this.hbuttonbox6.Add (this.button194);
		global::Gtk.ButtonBox.ButtonBoxChild w35 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button194]));
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button195 = new global::Gtk.Button ();
		this.button195.CanFocus = true;
		this.button195.Name = "button195";
		this.button195.UseUnderline = true;
		this.button195.Label = global::Mono.Unix.Catalog.GetString ("Upsert GPU Info");
		this.hbuttonbox6.Add (this.button195);
		global::Gtk.ButtonBox.ButtonBoxChild w36 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button195]));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button196 = new global::Gtk.Button ();
		this.button196.CanFocus = true;
		this.button196.Name = "button196";
		this.button196.UseUnderline = true;
		this.button196.Label = global::Mono.Unix.Catalog.GetString ("Upsert FabInfo");
		this.hbuttonbox6.Add (this.button196);
		global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button196]));
		w37.Position = 2;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.button197 = new global::Gtk.Button ();
		this.button197.CanFocus = true;
		this.button197.Name = "button197";
		this.button197.UseUnderline = true;
		this.button197.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbuttonbox6.Add (this.button197);
		global::Gtk.ButtonBox.ButtonBoxChild w38 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.button197]));
		w38.Position = 3;
		w38.Expand = false;
		w38.Fill = false;
		this.vbox3.Add (this.hbuttonbox6);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbuttonbox6]));
		w39.Position = 2;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow3.CanFocus = true;
		this.scrolledwindow3.Name = "scrolledwindow3";
		this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow3.Gtk.Container+ContainerChild
		this.textview3 = new global::Gtk.TextView ();
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.scrolledwindow3.Add (this.textview3);
		this.vbox3.Add (this.scrolledwindow3);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.scrolledwindow3]));
		w41.Position = 4;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w42.Position = 2;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1574;
		this.DefaultHeight = 772;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		this.button5.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
		this.button6.Clicked += new global::System.EventHandler (this.OnButton6Clicked);
		this.button61.Clicked += new global::System.EventHandler (this.OnButton61Clicked);
		this.button155.Clicked += new global::System.EventHandler (this.OnButton155Clicked);
		this.button194.Clicked += new global::System.EventHandler (this.OnButton194Clicked);
		this.button195.Clicked += new global::System.EventHandler (this.OnButton195Clicked);
		this.button196.Clicked += new global::System.EventHandler (this.OnButton196Clicked);
	}
}
